//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdoExamBooks
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Book_ShopEntities1 : DbContext
    {
        public Book_ShopEntities1()
            : base("name=Book_ShopEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Authors> Authors { get; set; }
        public virtual DbSet<Books> Books { get; set; }
        public virtual DbSet<Buyers> Buyers { get; set; }
        public virtual DbSet<Discounts> Discounts { get; set; }
        public virtual DbSet<NextTome> NextTome { get; set; }
        public virtual DbSet<Publishers> Publishers { get; set; }
        public virtual DbSet<Reservations> Reservations { get; set; }
        public virtual DbSet<Sales> Sales { get; set; }
        public virtual DbSet<Themes> Themes { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
