//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdoExamBooks
{
    using System;
    using System.Collections.Generic;
    
    public partial class NextTome
    {
        public int Id_NextTome { get; set; }
        public string Title { get; set; }
        public int Number { get; set; }
        public int Id_Book { get; set; }
    
        public virtual Books Books { get; set; }
    }
}
